image: ubuntu:latest

build:
  stage: build
  before_script:
    # Install build dependencies
    - apt update && apt -y install build-essential cmake nodejs=8.10.0~dfsg-2ubuntu0.2 nodejs-dev=8.10.0~dfsg-2ubuntu0.2 libcpprest-dev npm libssl-dev git
    - gcc --version
    - cmake --version

    # Install Angular dependencies
    - npm install -g @angular/cli
    - cd web/ && npm install && npm update && npm install && cd ../
  script:
    - cmake . -G "Unix Makefiles"
    - make
  artifacts:
    paths:
      - bin
      - lib
      - web/dist

test:
  stage: test
  script:
    - bin/testbeewatch

pages:
  stage: deploy
  before_script:
    - apt update && apt -y install build-essential cmake doxygen graphviz libcpprest-dev
  script:
    - cmake . -G "Unix Makefiles"
    - make doc
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
