image: resin/rpi-raspbian:stretch

build:
  stage: build
  before_script:
    - apt update && apt -y install build-essential cmake
    - gcc --version
    - cmake --version
  script:
    - cmake . -G "Unix Makefiles"
    - make
  artifacts:
    paths:
      - bin
      - lib

test:
  stage: test
  script:
    - bin/testbeewatch

pages:
  before_script:
    - apt update && apt -y install build-essential cmake doxygen graphviz
  script:
    - cmake . -G "Unix Makefiles"
    - make doc
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
