image: resin/rpi-raspbian:stretch

build:
  stage: build
  before_script:
    - apt update && apt -y install build-essential cmake
    - gcc --version
    - cmake --version
  script:
    - cmake . -G "Unix Makefiles"
    - make
  artifacts:
    paths:
      - bin
      - lib

test:
  stage: test
  script:
    - bin/testbeewatch

doc:
  stage: deploy
  script:
    - make doc
  artifacts:
    paths:
      - doc
