image: resin/rpi-raspbian:stretch

build:
  stage: build
  before_script:
    - apt update && apt -y install build-essential cmake wiringpi
    - gcc --version
    - cmake --version
  script:
    - cmake . -G "Unix Makefiles"
    - make
  artifacts:
    paths:
      - bin
      - lib

test:
  stage: test
  script:
    # Generate results file in junit format
    - bin/testbeewatch -r junit > testbeewatch-results.xml
    # Produce console output to fail CI on errors
    - bin/testbeewatch
  artifacts:
    paths:
      - test*-results.xml
